### ISSUE TITLE
Suggested corrections to the workshop modules

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-R/introR#43]
The corrections I am suggesting and where to find them are detailed below (as best I can). Most of it is spelling mistakes or missing words, but there are a few that address problems actually following along. 

01 
* Quick Links to Exercises and R code -- interactive misspelled in the first sentence
* Exercise 1 -- describe where to go to create a new project (step 3), detail which options should be chosen from the pop-up window for creating a new project (step 3), 
* Using functions -- some people who have never coded might not know the difference between what is in the script pane and what is in the Console pane
* Using packages -- Some other useful commands -- "packages" misspelled ("Lastly, a quick note on pacakges and libraries.")
* Exercise 2 -- state that the "Run" button will only run lines of code you have selected

02
* More basics -- Working in the Console -- "because" is misspelled twice, and recommendation is misspelled (after 3rd set of code)
* Reading data into R -- double backslash not shown in parentheses and "because" is misspelled (third paragraph)

03
* Data Manipulation in dplyr -- "the" misspelled before magrittr is introduced
* Merging Data -- "intuitive" misspelled in first paragraph
* Modify and Summarize -- reword end of this sentence, "First arrange() will re-order a data frame based on the values of a columns."
* Exercise 3 -- hyperlink in step 1 is broken, "this" misspelled in step 2b, words seem to be missing in "In the end, you should have with a data frame that includes all rows and columns GAGES-II sites for NM..." on step 4

04
* Summary Statistics -- "interquartile" is misspelled
* Exercise 1 -- step 1 needs a period before "Hint"

05
* Exercise 1 -- reword "mean value of across these between" (step 1), implications is misspelled (step 1), reword "build some linear models that build a linear model" (step 2), "chose" should be "choose" (step 2)

06
* Flow History -- update number of data points from 36379 to 36478

07 
* color is spelled "colour" throughout this entire workshop - might be worth mentioning that R accepts either
* Exercise 1 -- "nla_data" in step 2 has not been mentioned before this
* Customizing and saving ggplot2 plots -- Themes -- period is missing after "the themes vignette within ggplot2", ggsave() function should have "height" not "heigh" (this drops the warnings from 44 to 16, only ones regarding font)
* Exercise 2 -- step 1 is not clear

08
* Functions and Programming with R -- "because" is misspelled after the first example
* Functions and Programming with R -- for -- I did not understanding this statement "using the sum() example is a bit unfair since sum() is actually implemented in C"
* Exercise 1 -- uses the "nla_data" that was not available in module 07
* Reproducible Documents and Presentations -- Create a Document -- the example shows "output: pdf_document" when it should show "output: html_document"

09

* the first paragraph references EPA and not USGS 
* does the EPA disclaimer need to be present at the very end?

**Comment by lawinslow** [comment]
Thanks @lindsaycarr, these look good. @ldecicco-USGS should these suggestions go into USGS-R/gsintroR? Maybe Lindsay could do a PR there?

**Comment by ldecicco-USGS** [comment]
That would be super.

**Comment by lindsaycarr** [comment]
@ldecicco-USGS should I go ahead and fork the USGS-R/gsintroR and get it onto my computer? I will need some guidance after to actually edit the material.

**Comment by ldecicco-USGS** [comment]
yeah, let me come give you a quick overview.
